### ISSUE TITLE
Issues running web-ext tests on node >= 8

### ISSUE THREAD

**Issue by rpl** [mozilla/web-ext#1129]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

Running the tests on node >= 8 currently fails due to the following errors:

- 'RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined' errors raised
  while running the following unit tests:
  - tests/unit/test-extension-runners/test.extension-runners.js
  - tests/unit/test-util/test.logger.js

```
 RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at new ReadStream (tty.js:41:11)
      at _callee10$ (dist/webpack:/tests/unit/test-extension-runners/test.extension-runners.js:489:25)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)
      at dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1
      at new Promise (<anonymous>)
      at new F (dist/webpack:/node_modules/core-js/library/modules/_export.js:35:1)
      at Context.<anonymous> (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1)
```

- 'TypeError: "cwd" must be a string' errors raised from the functional tests

```
TypeError: "cwd" must be a string
      at normalizeSpawnArguments (child_process.js:403:11)
      at exports.spawn (child_process.js:496:38)
      at execWebExt (dist/webpack:/tests/functional/common.js:97:26)
      at dist/webpack:/tests/functional/test.cli.build.js:12:20
      at dist/webpack:/tests/functional/common.js:52:16
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

The complete failures logs are available in the following travis job:

- https://travis-ci.org/rpl/web-ext/jobs/296748492

### What is the expected or desired behavior?

The tests (and web-ext) should be able to run successfully on node >= 8

### Version information (for bug reports)

OS: any
node: v8.9.0
npm: 5.5.1

**Comment by hiikezoe** [comment]
I've been seeing the first error locally, and it should be fixed by https://github.com/facebook/flow/pull/5992.

**Comment by hiikezoe** [comment]
Of course, flow-bin should be updated to corresponding version and rewrite 'new tty.ReadStream()' with 'new tty.ReadStream(0)'.

**Comment by Rob--W** [comment]
This should be re-opened. PR #1293 said that it will fix this bug partially.
Indeed, I am still getting 14 errors with `ERR_INVALID_FD` when I run `grunt test:unit:run`:

```
  2) util/extension-runners
       defaultReloadStrategy
         can reload when user presses R in shell console:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at new ReadStream (tty.js:46:11)                                                                                                                                                                                                                                         
      at _callee10$ (dist/webpack:/tests/unit/test-extension-runners/test.extension-runners.js:483:25)                                                                                                                                                                         
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)                                                                                                                                                                                                          
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)                                                                                                                                                                                    
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)                                                                                                                                                               
      at step (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)                                                                                                                                                                                      
      at dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1                                                                                                                                                                                             
      at new Promise (<anonymous>)                                                                                                                                                                                                                                             
      at new F (dist/webpack:/node_modules/core-js/library/modules/_export.js:36:1)                                                                                                                                                                                            
      at Context.<anonymous> (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1)                                                                                                                                                                       
      at process.topLevelDomainCallback (domain.js:102:23)                                                                                                                                                                                                                     

  3) util/extension-runners
       defaultReloadStrategy
         allows you to disable input:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at new ReadStream (tty.js:46:11)                                                                                                                                                                                                                                         
      at _callee11$ (dist/webpack:/tests/unit/test-extension-runners/test.extension-runners.js:505:25)                                                                                                                                                                         
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)                                                                                                                                                                                                          
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)                                                                                                                                                                                    
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)                                                                                                                                                               
      at step (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)                                                                                                                                                                                      
      at dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1                                                                                                                                                                                             
      at new Promise (<anonymous>)                                                                                                                                                                                                                                             
      at new F (dist/webpack:/node_modules/core-js/library/modules/_export.js:36:1)                                                                                                                                                                                            
      at Context.<anonymous> (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1)                                                                                                                                                                       
      at process.topLevelDomainCallback (domain.js:102:23)                                                                                                                                                                                                                     

  4) util/extension-runners
       defaultReloadStrategy
         can still reload when user presses R after a reload error:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at new ReadStream (tty.js:46:11)                                                                                                                                                                                                                                         
      at _callee12$ (dist/webpack:/tests/unit/test-extension-runners/test.extension-runners.js:532:28)                                                                                                                                                                         
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)                                                                                                                                                                                                          
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)                                                                                                                                                                                    
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)                                                                                                                                                               
      at step (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)                                                                                                                                                                                      
      at dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1                                                                                                                                                                                             
      at new Promise (<anonymous>)                                                                                                                                                                                                                                             
      at new F (dist/webpack:/node_modules/core-js/library/modules/_export.js:36:1)                                                                                                                                                                                            
      at Context.<anonymous> (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1)                                                                                                                                                                       
      at process.topLevelDomainCallback (domain.js:102:23)                                                                                                                                                                                                                     

  5) util/extension-runners
       defaultReloadStrategy
         shuts down firefox on user request (CTRL+C in shell console):
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at new ReadStream (tty.js:46:11)                                                                                                                                                                                                                                         
      at _callee14$ (dist/webpack:/tests/unit/test-extension-runners/test.extension-runners.js:562:28)                                                                                                                                                                         
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)                                                                                                                                                                                                          
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)                                                                                                                                                                                    
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)                                                                                                                                                               
      at step (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)                                                                                                                                                                                      
      at dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1                                                                                                                                                                                             
      at new Promise (<anonymous>)                                                                                                                                                                                                                                             
      at new F (dist/webpack:/node_modules/core-js/library/modules/_export.js:36:1)                                                                                                                                                                                            
      at Context.<anonymous> (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1)                                                                                                                                                                       
      at process.topLevelDomainCallback (domain.js:102:23)                                                                                                                                                                                                                     

  6) util/extension-runners
       defaultReloadStrategy
         pauses the web-ext process (CTRL+Z in shell console):
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at new ReadStream (tty.js:46:11)                                                                                                                                                                                                                                         
      at _callee15$ (dist/webpack:/tests/unit/test-extension-runners/test.extension-runners.js:583:25)                                                                                                                                                                         
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)                                                                                                                                                                                                          
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)                                                                                                                                                                                    
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)                                                                                                                                                               
      at step (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)                                                                                                                                                                                      
      at dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1                                                                                                                                                                                             
      at new Promise (<anonymous>)                                                                                                                                                                                                                                             
      at new F (dist/webpack:/node_modules/core-js/library/modules/_export.js:36:1)                                                                                                                                                                                            
      at Context.<anonymous> (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1)                                                                                                                                                                       
      at process.topLevelDomainCallback (domain.js:102:23)                                                                                                                                                                                                                     

  7) util/extension-runners/firefox-android
       a valid device and Firefox apk has been selected:
         allows user to exit while waiting for the Android Firefox Debugger:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at new ReadStream (tty.js:46:11)                                                                                                                                                                                                                                         
      at _callee20$ (dist/webpack:/tests/unit/test-extension-runners/test.firefox-android.js:591:28)                                                                                                                                                                           
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)                                                                                                                                                                                                          
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)                                                                                                                                                                                    
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)                                                                                                                                                               
      at step (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)                                                                                                                                                                                      
      at dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1                                                                                                                                                                                             
      at new Promise (<anonymous>)                                                                                                                                                                                                                                             
      at new F (dist/webpack:/node_modules/core-js/library/modules/_export.js:36:1)                                                                                                                                                                                            
      at Context.<anonymous> (dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1)                                                                                                                                                                       
      at process.topLevelDomainCallback (domain.js:102:23)                                                                                                                                                                                                                     

  8) logger
       ConsoleStream
         does not log debug packets unless verbose:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at FakeWritableStream.WriteStream (tty.js:72:11)                                                                                                                                                                                                                         
      at new FakeWritableStream (dist/webpack:/tests/unit/test-util/test.logger.js:39:28)                                                                                                                                                                                      
      at fakeProcess (dist/webpack:/tests/unit/test-util/test.logger.js:46:34)                                                                                                                                                                                                 
      at Context.<anonymous> (dist/webpack:/tests/unit/test-util/test.logger.js:80:28)                                                                                                                                                                                         
      at process.topLevelDomainCallback (domain.js:102:23)                                                                                                                                                                                                                     

  9) logger
       ConsoleStream
         does not log trace packets unless verbose:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at FakeWritableStream.WriteStream (tty.js:72:11)                                                                                                                                                                                                                         
      at new FakeWritableStream (dist/webpack:/tests/unit/test-util/test.logger.js:39:28)                                                                                                                                                                                      
      at fakeProcess (dist/webpack:/tests/unit/test-util/test.logger.js:46:34)                                                                                                                                                                                                 
      at Context.<anonymous> (dist/webpack:/tests/unit/test-util/test.logger.js:88:28)                                                                                                                                                                                         
      at process.topLevelDomainCallback (domain.js:102:23)                                                                                                                                                                                                                     

  10) logger
       ConsoleStream
         logs debug packets when verbose:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at FakeWritableStream.WriteStream (tty.js:72:11)
      at new FakeWritableStream (dist/webpack:/tests/unit/test-util/test.logger.js:39:28)
      at fakeProcess (dist/webpack:/tests/unit/test-util/test.logger.js:46:34)
      at Context.<anonymous> (dist/webpack:/tests/unit/test-util/test.logger.js:96:28)
      at process.topLevelDomainCallback (domain.js:102:23)

  11) logger
       ConsoleStream
         logs trace packets when verbose:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at FakeWritableStream.WriteStream (tty.js:72:11)
      at new FakeWritableStream (dist/webpack:/tests/unit/test-util/test.logger.js:39:28)
      at fakeProcess (dist/webpack:/tests/unit/test-util/test.logger.js:46:34)
      at Context.<anonymous> (dist/webpack:/tests/unit/test-util/test.logger.js:104:28)
      at process.topLevelDomainCallback (domain.js:102:23)

  12) logger
       ConsoleStream
         logs info packets when verbose or not:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at FakeWritableStream.WriteStream (tty.js:72:11)
      at new FakeWritableStream (dist/webpack:/tests/unit/test-util/test.logger.js:39:28)
      at fakeProcess (dist/webpack:/tests/unit/test-util/test.logger.js:46:34)
      at Context.<anonymous> (dist/webpack:/tests/unit/test-util/test.logger.js:112:28)
      at process.topLevelDomainCallback (domain.js:102:23)

  13) logger
       ConsoleStream
         lets you capture logging:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at FakeWritableStream.WriteStream (tty.js:72:11)
      at new FakeWritableStream (dist/webpack:/tests/unit/test-util/test.logger.js:39:28)
      at fakeProcess (dist/webpack:/tests/unit/test-util/test.logger.js:46:34)
      at Context.<anonymous> (dist/webpack:/tests/unit/test-util/test.logger.js:123:28)
      at process.topLevelDomainCallback (domain.js:102:23)

  14) logger
       ConsoleStream
         only flushes captured messages once:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at FakeWritableStream.WriteStream (tty.js:72:11)
      at new FakeWritableStream (dist/webpack:/tests/unit/test-util/test.logger.js:39:28)
      at fakeProcess (dist/webpack:/tests/unit/test-util/test.logger.js:46:34)
      at Context.<anonymous> (dist/webpack:/tests/unit/test-util/test.logger.js:136:26)
      at process.topLevelDomainCallback (domain.js:102:23)

  15) logger
       ConsoleStream
         lets you start and stop capturing:
     RangeError [ERR_INVALID_FD]: "fd" must be a positive integer: undefined
      at FakeWritableStream.WriteStream (tty.js:72:11)
      at new FakeWritableStream (dist/webpack:/tests/unit/test-util/test.logger.js:39:28)
      at fakeProcess (dist/webpack:/tests/unit/test-util/test.logger.js:46:34)
      at Context.<anonymous> (dist/webpack:/tests/unit/test-util/test.logger.js:153:26)
      at process.topLevelDomainCallback (domain.js:102:23)



Warning: Task "mochaTest:unit" failed. Use --force to continue.
```

**Comment by yan12125** [comment]
I can confirm this is still an issue. Tested with node.js v10.0.0 on Arch Linux.

**Comment by rpl** [comment]
Closed by #1310

**Comment by suedar** [comment]
Hey.Did you find the solution of this problem?
